layout_spectrum: 0.8757470194250345
typography_spectrum: 0.49916831823065877
color:
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
  brandStrength: 0.10955245257355273
  lightness: 0.1948614886496216
  saturation: 0.2610455662943423
  rhythmicContrast: 0.46245588758029044
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Anthony Carboni
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Anthony Carboni
description: Oh jeez man I don't know
purpose: []
